<img width="10%" alt="Naas" src="https://landen.imgix.net/jtci2pxwjczr/assets/5ice39g4.png?w=160"/>

# LinkedIn - List top company contents
<a href="https://app.naas.ai/user-redirect/naas/downloader?url=https://raw.githubusercontent.com/jupyter-naas/awesome-notebooks/master/LinkedIn/Linkedin_Follow_number_of_content_published.ipynb" target="_parent"><img src="https://naasai-public.s3.eu-west-3.amazonaws.com/open_in_naas.svg"/></a>

**Tags:** #linkedin #html #plotly #csv #image #content #analytics #automation

**Author:** [Florent Ravenel](https://www.linkedin.com/in/florent-ravenel/)

## Input

In [1]:
# Except allow to run common.ipynb once using Naas Engine
try:
    %run "../common.ipynb"
except:
    %run "common.ipynb"

### Setup Variables

In [2]:
KPI_TITLE = "Top posts"
INPUT_DATABASE = LK_COMPANY_POSTS
OWNER = LK_COMPANY_NAME
OWNER_ID = LK_COMPANY_ID
PLATFORM = LINKEDIN
LOGO = LINKEDIN_LOGO
COLOR = LINKEDIN_COLOR

### Setup Constants

In [3]:
# Inputs
SCENARIO = SCENARIO_MTD
PERIOD = PERIOD_MTD
PERIOD_D = DISPLAY_MTD
PERIOD_TEXT = TEXT_MTD
PERIOD_TEXT2 = TEXT2_MTD

## Model

### Get your posts

In [4]:
df_posts = get_data(INPUT_DATABASE)
print("✅ Posts fetched:", len(df_posts))
df_posts.head(1)

✅ Posts fetched: 126

,ACTIVITY_ID,PUBLISHED_DATE,AUTHOR_NAME,AUTHOR_URL,SUBDESCRIPTION,TITLE,TEXT,CHARACTER_COUNT,TAGS,TAGS_COUNT,...,POLL_ID,POLL_QUESTION,POLL_RESULTS,POST_URL,VIEWS,COMMENTS,LIKES,SHARES,ENGAGEMENT_SCORE,DATE_EXTRACT
0,6946860124556681216,2022-06-26 16:22:00+02:00,naas.ai,https://www.linkedin.com/company/70506391,23 hours ago,No comment. 👌,No comment. 👌,13,NaN,0,...,NaN,NaN,NaN,https://www.linkedin.com/feed/update/urn:li:ac...,221,0,2,0,0.00905,2022-06-27 18:21:50

### Get top posts

In [5]:
def get_posts(df_init,
              col_date):
    
    # Init variable
    df = df_init.copy()
    df["VIEWS"] = df["VIEWS"].astype(int)
    df["LIKES"] = df["LIKES"].astype(int)
    df["COMMENTS"] = df["COMMENTS"].astype(int)
    df["ENGAGEMENT_SCORE"] = df["ENGAGEMENT_SCORE"].astype(float)
    df[SCENARIO] = pd.to_datetime(df[col_date].str[:-6]).dt.strftime(PERIOD)
    
    # Filter
    df = df[df[SCENARIO] == datetime.now().strftime(PERIOD)].reset_index(drop=True)
    
    # Sort
    df = df.sort_values(by="VIEWS", ascending=False)
    
    # Order
    df = df[["TITLE", "PUBLISHED_DATE", "AUTHOR_NAME", "POST_URL", "VIEWS", "LIKES", "COMMENTS", "SHARES", "ENGAGEMENT_SCORE"]]
    return df.reset_index(drop=True)

df_top = get_posts(df_posts,
                   col_date="PUBLISHED_DATE")
df_top

,TITLE,PUBLISHED_DATE,AUTHOR_NAME,POST_URL,VIEWS,LIKES,COMMENTS,SHARES,ENGAGEMENT_SCORE
0,Want to use AI to label the sentiment of your ...,2022-06-20 11:33:33+02:00,naas.ai,https://www.linkedin.com/feed/update/urn:li:ac...,743,11,2,0,0.017497
1,Wondering how to read a dataframe from your fi...,2022-06-16 12:59:30+02:00,naas.ai,https://www.linkedin.com/feed/update/urn:li:ac...,431,9,0,0,0.020882
2,Good read !,2022-06-14 19:41:52+02:00,naas.ai,https://www.linkedin.com/feed/update/urn:li:ac...,397,3,1,0,0.010076
3,Did you know you can send daily billing notifi...,2022-06-16 07:36:22+02:00,naas.ai,https://www.linkedin.com/feed/update/urn:li:ac...,367,6,0,0,0.016349
4,Critical thinking and problem solving is very ...,2022-06-16 12:08:40+02:00,naas.ai,https://www.linkedin.com/feed/update/urn:li:ac...,351,3,2,0,0.014245
5,⚡️ We started a challenge this Monday: aggrega...,2022-06-15 06:44:27+02:00,naas.ai,https://www.linkedin.com/feed/update/urn:li:ac...,345,9,0,0,0.026087
6,Dashboards do not need to be perfect the first...,2022-06-14 12:54:42+02:00,naas.ai,https://www.linkedin.com/feed/update/urn:li:ac...,318,3,2,0,0.015723
7,Do you want to download files in your AWS buck...,2022-06-16 10:50:00+02:00,naas.ai,https://www.linkedin.com/feed/update/urn:li:ac...,307,3,0,0,0.009772
8,Build your company metrics database with naas....,2022-06-02 12:53:31+02:00,naas.ai,https://www.linkedin.com/feed/update/urn:li:ac...,268,3,0,0,0.011194
9,No comment. 👌,2022-06-26 16:22:00+02:00,naas.ai,https://www.linkedin.com/feed/update/urn:li:ac...,221,2,0,0,0.009050
10,Most of the people working in data think noteb...,2022-06-22 17:52:09+02:00,naas.ai,https://www.linkedin.com/feed/update/urn:li:ac...,218,7,0,0,0.032110
11,🤙 Nikolaj Groeneweg is putting together someth...,2022-06-08 19:39:38+02:00,naas.ai,https://www.linkedin.com/feed/update/urn:li:ac...,178,4,0,0,0.022472
12,"Rules based approach comes first, and ML can b...",2022-06-11 07:09:40+02:00,naas.ai,https://www.linkedin.com/feed/update/urn:li:ac...,161,3,0,0,0.018634
13,Congrats Alok Chilka!,2022-06-07 18:44:48+02:00,naas.ai,https://www.linkedin.com/feed/update/urn:li:ac...,103,2,0,0,0.019417
14,💎 Brand your charts with your company logo!,2022-06-11 07:19:26+02:00,naas.ai,https://www.linkedin.com/feed/update/urn:li:ac...,61,0,0,0,0.000000
15,💚🤙,2022-06-11 07:14:43+02:00,naas.ai,https://www.linkedin.com/feed/update/urn:li:ac...,58,2,0,0,0.034483

## Output

### Update Notion Report

In [6]:
def update_report_status(report,
                         platform,
                         owner,
                         df=pd.DataFrame(),
                         image_link=None,
                         html_link=None,
                         csv_link=None,
                         page_icon=LOGO,
                         ):
    # Decode database id
    database_id = naas.secret.get(name="NOTION_DATABASE_URL").split("/")[-1].split("?v=")[0]
    
    # Get pages from notion database
    pages = notion.connect(NOTION_TOKEN).database.query(database_id)
    
    # Create or update page
    page_new = True
    for page in pages:
        page_temp = page.df()
        page_id = page_temp.loc[page_temp.Name == "Report name", "Value"].values
        page_id2 = page_temp.loc[page_temp.Name == "Platform", "Value"].values
        page_id3 = page_temp.loc[page_temp.Name == "Owner", "Value"].values
        if page_id == report and page_id2 == platform and page_id3 == owner:
            page_new = False
            break
    try:
        if page_new:
            page = notion.connect(NOTION_TOKEN).Page.new(database_id=database_id).create()
            page.title("Report name", report)
            page.multi_select("Platform", [platform])
            page.select("Owner", owner)
            notion.client.pages.update(page_id=page.id, icon={'type': 'external', 'external': {'url': page_icon}})
            
        # Check if image already exists
        blocks = page.get_blocks()
        if len(blocks) > 0:
            while True:
                for block in blocks:
                    notion.connect(NOTION_TOKEN).blocks.delete(block.id)
                blocks = page.get_blocks()
                if len(blocks) == 0:
                    break
        page.update()
        
        kpis = ["ENGAGEMENT_SCORE", "VIEWS", "COMMENTS", "LIKES"]
        for kpi in kpis:
            heading_3 = f"By {kpi.lower()}"
            if kpi == "ENGAGEMENT_SCORE":
                heading_3 = "By engagement rate"
            page.heading_3(heading_3)
            tmp_df = df.sort_values(by=kpi, ascending=False).reset_index(drop=True)[:3]
            for index, row in tmp_df.iterrows():
                value = row[kpi]
                kpi_d = kpi.lower()
                title = f"{row.TITLE} ({value} {kpi_d})"
                if kpi == "ENGAGEMENT_SCORE":
                    value = "{:,.2%}".format(value)
                    title = f"{row.TITLE} ({value})"
                res = page.numbered_list_item(title)
                res.numbered_list_item.text[0].href = row.POST_URL
                res.numbered_list_item.text[0].text.link = Link(row.POST_URL)
            
        # Create page in Notion
        page.date("Last updated date", datetime.now(pytz.timezone(TIMEZONE)).strftime("%Y-%m-%d %H:%M:%S%z"))
        page.update()
        print(f"✅ Page '{report} - {platform} - {owner}' updated in Notion.")
    except Exception as e:
        raise(e)

update_report_status(KPI_TITLE,
                     PLATFORM,
                     OWNER,
                     df_top)

✅ Page 'Top posts - LinkedIn - naas.ai' updated in Notion.