<img width="10%" alt="Naas" src="https://landen.imgix.net/jtci2pxwjczr/assets/5ice39g4.png?w=160"/>

# LinkedIn - List new connections monthly
<a href="https://app.naas.ai/user-redirect/naas/downloader?url=https://raw.githubusercontent.com/jupyter-naas/awesome-notebooks/master/LinkedIn/Linkedin_Follow_number_of_content_published.ipynb" target="_parent"><img src="https://naasai-public.s3.eu-west-3.amazonaws.com/open_in_naas.svg"/></a>

**Tags:** #linkedin #html #plotly #csv #image #content #analytics #automation

**Author:** [Florent Ravenel](https://www.linkedin.com/in/florent-ravenel/)

## Input

### Get common variables, functions

In [1]:
# Get common path and run it
from os import path

common_path = "../common.ipynb"
if not path.exists(common_path):
    common_path = f"{naas.secret.get('GIT_REPO_NAME')}/common.ipynb"

%run "$common_path"

### Setup Variables

In [2]:
KPI_TITLE = "New connections"

### Setup Constants

In [3]:
# Inputs
PLATFORM = LINKEDIN
LOGO = LINKEDIN_LOGO
OWNER = LK_FULLNAME
SCENARIO = SCENARIO_MTD
PERIOD = PERIOD_MTD
COL_DATE = "CREATED_AT"

# Input
csv_input = path.join(LINKEDIN_OUTPUTS, f"LINKEDIN_FOLLOW_PROFILE_CONNECTIONS_{SCENARIO}_{LK_PROFILE_ID}.csv")

## Model

### Get connections from LinkedIn network

In [4]:
df_connections = get_data(LK_PROFILE_CONNECTIONS)
print("Data fetched:", len(df_connections))
df_connections.head(1)

Data fetched: 2317

,FIRSTNAME,LASTNAME,OCCUPATION,CREATED_AT,PROFILE_URL,PROFILE_PICTURE,PROFILE_ID,PUBLIC_ID,DATE_EXTRACT,OWNER_ID,OWNER_NAME
0,Sugato,Ray,Datapreneur,2022-07-13 11:33:54,https://www.linkedin.com/in/ACoAAAXOAb0BI_0E2J...,https://media-exp2.licdn.com/dms/image/C4D03AQ...,ACoAAAXOAb0BI_0E2JdcKX7ehPM2YAZdVNcTFoY,raysugato,2022-07-13 16:42:31,ACoAABCNSioBW3YZHc2lBHVG0E_TXYWitQkmwog,Florent Ravenel

### Get data

In [5]:
def calc_value(csv_input):
    df = get_data(csv_input)
    if len(df) > 0:
        value = df.loc[df.index[-1], "VARV"]
        value_comp = df.loc[df.index[-2], "VARV"]
        varv = value - value_comp
        varp = varv / abs(value_comp)
        return value, value_comp, varv, varp
    else:
        return 0, 0, 0, 0

value, value_comp, varv, varp = calc_value(csv_input)
# print(value, value_comp, varv, varp)

### Get list

In [6]:
def get_list(df_init,
              col_date):
    
    # Init variable
    df = df_init.copy()
    df[SCENARIO] = pd.to_datetime(df[col_date]).dt.strftime(PERIOD)
    df["DATE"] = pd.to_datetime(df[col_date]).dt.strftime("%Y-%m-%d")
    df["DATE_NUMBER"] = pd.to_datetime(df[col_date]).dt.strftime("%Y%m%d")
    df["HOURS"] = pd.to_datetime(df[col_date]).dt.strftime("%H:%M:%S")
    
    # Filter
    df = df[df[SCENARIO] == datetime.now().strftime(PERIOD)].reset_index(drop=True)
    
    # Sort
    df = df.sort_values(by=col_date, ascending=False)
    return df.reset_index(drop=True)

df_new = get_list(df_connections,
                  col_date=COL_DATE)
print("New rows:", len(df_new))
df_new.head(1)

New rows: 62

,FIRSTNAME,LASTNAME,OCCUPATION,CREATED_AT,PROFILE_URL,PROFILE_PICTURE,PROFILE_ID,PUBLIC_ID,DATE_EXTRACT,OWNER_ID,OWNER_NAME,MTD,DATE,DATE_NUMBER,HOURS
0,Sugato,Ray,Datapreneur,2022-07-13 11:33:54,https://www.linkedin.com/in/ACoAAAXOAb0BI_0E2J...,https://media-exp2.licdn.com/dms/image/C4D03AQ...,ACoAAAXOAb0BI_0E2JdcKX7ehPM2YAZdVNcTFoY,raysugato,2022-07-13 16:42:31,ACoAABCNSioBW3YZHc2lBHVG0E_TXYWitQkmwog,Florent Ravenel,2022-07,2022-07-13,20220713,11:33:54

## Output

### Update Notion Report

In [14]:
page = list_new_connections(KPI_TITLE,
                            PLATFORM,
                            OWNER,
                            df_new)

✅ Page 'New connections - LinkedIn - Florent Ravenel' updated in Notion.